// Generated by CoffeeScript 1.4.0

/*
//>>excludeStart("umobiBuildExclude", pragmas.umobiBuildExclude)
*/


(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['cs!umobi.core'], function() {
    /*
      //>>excludeEnd("umobiBuildExclude")
    */

    var support;
    support = {
      offlineCache: typeof window.applicationCache !== 'undefined',
      classList: typeof document.documentElement !== 'undefined',
      touch: navigator.userAgent.match(/(iPhone|iPad|Android|Mobile)/)
    };
    support.matrix = "WebKitCSSMatrix" in window;
    support.matrixM11 = support.matrix && (__indexOf.call(new WebKitCSSMatrix(), "m11") >= 0);
    umobi.support = support;
    /*
      //>>excludeStart("umobiBuildExclude", pragmas.umobiBuildExclude)`
    */

    return umobi.support;
  });

  /*
  //>>excludeEnd("umobiBuildExclude")
  */


}).call(this);
