// Generated by CoffeeScript 1.4.0
(function() {

  define(["cs!str", "cs!umobi.core", "cs!u", "cs!umobi.page", "cs!umobi.button"], function() {
    /*
      To inner wrap a link with ui-btn classes:
    
      <a href="index.html" data-role="button" data-corners="true"
        data-shadow="true" data-iconshadow="true" data-wrapperels="span"
        data-theme="c" class="ui-btn ui-shadow ui-btn-corner-all ui-btn-up-c">
          <span class="ui-btn-inner ui-btn-corner-all">
            <span class="ui-btn-text">Link button</span>
          </span>
      </a>
    */
    (function() {
      return u.ready(function() {
        var link, ulink, _i, _len, _ref, _results;
        _ref = document.links;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          link = _ref[_i];
          ulink = u(link);
          if (!ulink.data('role'))  
            ulink.addClass('ui-link');
          _results.push(ulink.click(function(e) {
            var hash, href, regs;
            href = ulink.attr("href");
            if (/^#\w+/)  
              umobi.page.revealByHash(href);
            regs = href.match(/(#\w+)/);
            hash = regs ? regs[1] : "#index";
            if (ulink.data("ajax")) {
              e.preventDefault();
              $.ajax({
                url: href,
                dataType: "html",
                success: function(html) {
                  var $body, $page, body;
                  body = document.createElement("body");
                  body.innerHTML = html;
                  $body = $(body);
                  $page = $body.find(hash);
                  if (!$page.get(0))  
                    $page = $body.find('[data-role="page"]').first();
                  return $(document.body).append($page);
                },
                error: function(err) {
                  return console.error("error", err);
                }
              });
              return false; 
            }
          }));
        }
        return _results;
      });
    })();
  });

}).call(this);
