// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var dom;
    dom = {};
    /*
      # See if current DOM support classList (HTML5)
    */

    dom.supportClassList = typeof document.documentElement.classList !== "undefined";
    dom.query = function(q, c) {
      c = c || document;
      return c.querySelector(q);
    };
    dom.queryAll = function(q, c) {
      c = c || document;
      if (!c.querySelectorAll) {
        throw new Error("Object " + typeof c + " does not contains querySelectorAll method"); 
      }
      return c.querySelectorAll(q);
    };
    dom.get = function(dom, c) {
      c = c || document;
      return c.getElementById(dom);
    };
    dom.collectionToArray = function(c) {
      var i, len, list;
      i = 0;
      len = c.length;
      list = [];
      while (i < len) {
        list.push(c[i]);
        i++;
      }
      return list;
    };
    dom.byTagName = function(n, c) {
      c = c || document;
      return c.getElementsByTagName(n);
    };
    dom.byClassName = function(n, c) {
      c = c || document;
      return c.getElementsByClassName(n);
    };
    dom.bind = function(el, n, cb) {
      return el.addEventListener(n, cb);
    };
    window.dom = dom;
    return window.dom;
  });

}).call(this);
