// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery", "cs!umobi.core", "cs!u"], function() {
    var TapDetector;
    TapDetector = (function() {

      TapDetector.prototype.moved = false;

      function TapDetector(element) {
        this.element = element;
        this.element.addEventListener("touchstart", this, false);
      }

      TapDetector.prototype.handleEvent = function(e) {
        switch (e.type) {
          case "touchmove":
            return this.onTouchMove(e);
          case "touchstart":
            return this.onTouchStart(e);
          case "touchend":
            return this.onTouchEnd(e);
        }
      };

      TapDetector.prototype.onTouchStart = function(e) {
        var _this = this;
        this.moved = false;
        this.theTarget = document.elementFromPoint(e.targetTouches[0].clientX, e.targetTouches[0].clientY);
        this._t = setTimeout((function() {}), 200);
        this.element.addEventListener("touchmove", this, false);
        return this.element.addEventListener("touchend", this, false);
      };

      TapDetector.prototype.onTouchMove = function(e) {
        this.moved = true;
        return clearTimeout(this._t);
      };

      TapDetector.prototype.onTouchEnd = function(e) {
        this.element.removeEventListener("touchmove", this, false);
        this.element.removeEventListener("touchend", this, false);
        if (!this.moved && this.theTarget)  
          return $(this.theTarget).trigger("tap");
      };

      return TapDetector;

    })();
    u.ready(function() {
      return $("a,button").each(function(i, e) {
        return new TapDetector(this);
      });
    });
  });

}).call(this);
