// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery", "cs!umobi.core", "cs!u"], function() {
    $(function() {
      var $input, input, inputs, textareas, uiClass, _i, _j, _len, _len1, _ref, _ref1, _results;
      inputs = u('input[type="text"],input[type="password"]');
      _ref = inputs.all();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        input = _ref[_i];
        $input = $(input);
        uiClass = "ui-input-text";
        input.className += uiClass;
        $input.wrap('<div class="' + uiClass + ' ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c"></div>');
        $input.focus(function() {
          return $(this).parent().addClass('ui-focus');
        });
        $input.blur(function() {
          return $(this).parent().removeClass('ui-focus');
        });
        if ($input.data("mini"))  
          $input.parent().addClass("ui-mini");
      }
      textareas = u('textarea');
      _ref1 = textareas.all();
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        input = _ref1[_j];
        input.className += "ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c";
        $input.focus(function() {
          return $(this).addClass('ui-focus');
        });
        $input.blur(function() {
          return $(this).removeClass('ui-focus');
        });
        if ($input.data("mini")) {
          _results.push($input.parent().addClass("ui-mini")); 
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  });

}).call(this);
