// Generated by CoffeeScript 1.4.0
(function() {

  define(["cs!u", "cs!umobi.core", "cs!umobi.page"], function() {
    var f, tag, tags, _i, _len, _results;
    tags = ["article", "section", "header", "footer", "aside", "details", "summary", "page"];
    f = document.createDocumentFragment();
    _results = [];
    for (_i = 0, _len = tags.length; _i < _len; _i++) {
      tag = tags[_i];
      _results.push(f.appendChild(d.createElement(tag)));
    }
    return _results;
  });

}).call(this);
