// Generated by CoffeeScript 1.4.0
(function() {
  var __slice = [].slice;

  define([], function() {
    String.prototype.toCapitalCase = function() {
      return this.charAt(0).toUpperCase() + this.substr(1);
    };
    String.prototype.toCamelCase = function() {
      return (this.toWords().map(function(p) {
        return p.toCapitalCase();
      })).join('');
    };
    String.prototype.toLowerCamelCase = function() {
      var first, rest, _ref;
      _ref = this.toWords(), first = _ref[0], rest = 2 <= _ref.length ? __slice.call(_ref, 1) : [];
      return first + (rest.map(function(p) {
        return p.toCapitalCase();
      })).join('');
    };
    String.prototype.toWords = function() {
      return this.split(/[-_,\.]+/);
    };
    return String.prototype.toDashCase = function() {
      return this.replace(/([A-Z])/g, function(v) {
        return '-' + v.toLowerCase();
      }).replace(/^-/, '');
    };
  });

}).call(this);
