// Generated by CoffeeScript 1.4.0
(function() {

  define(["cs!u.dom", "cs!u"], function() {
    u._widgets = {};
    /*
      Widget base class
    */

    u.Widget = (function() {

      function Widget() {}

      return Widget;

    })();
    /*
      Widget factory method
      
         @param string name
         @param closure factory
    */

    return u.widget = function(name, factory) {
      if (factory)  
        return u[name] = function(options) {
          return factory.apply(options);
        };
    };
  });

}).call(this);
