// Generated by CoffeeScript 1.4.0
(function() {

  define(["cs!u", "cs!umobi.core", "cs!umobi.page", "cs!umobi.widget", "cs!umobi.zoom", "cs!umobi.listview", "cs!umobi.navigation"], function() {
    (function(d) {
      var uhtml;
      (function() {
        var f, tag, tags, _i, _len, _results;
        tags = ["article", "section", "header", "footer", "aside", "details", "summary", "page"];
        f = document.createDocumentFragment();
        _results = [];
        for (_i = 0, _len = tags.length; _i < _len; _i++) {
          tag = tags[_i];
          _results.push(f.appendChild(d.createElement(tag)));
        }
        return _results;
      })();
      uhtml = u('html');
      uhtml.children(0).addClass(['ui-mobile', 'ui-mobile-rendering']);
      return u.ready(function() {
        var hideAddressBar;
        umobi.page.init();
        if (window.navigator.userAgent.match(/iPhone|iPad|Android/)) {
          if (window.console)  
            console.log("touch enabled deviced");
          hideAddressBar = function() {
            if (document.documentElement.scrollHeight < (window.outerHeight / window.devicePixelRatio))  
              document.documentElement.style.height = (window.outerHeight / window.devicePixelRatio) + 'px';
            return window.scrollTo(0, 1);
          };
          window.addEventListener("load", hideAddressBar);
          window.addEventListener("orientationchange", hideAddressBar);
          $(document).on('pagereveal', hideAddressBar); 
        }
        u.load(function() {
          return uhtml.removeClass('ui-mobile-rendering');
        });
        return u(document.body).addClass("ui-body-c");
      });
    })(document);
  });

}).call(this);
