// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'cs!umobi.core', 'cs!u'], function() {
    var disabledInitially, disabledZoom, enabledZoom, initialContent, meta;
    meta = $("meta[name=viewport]");
    initialContent = meta.attr("content");
    disabledZoom = initialContent + ",maximum-scale=1, user-scalable=no";
    enabledZoom = initialContent + ",maximum-scale=10, user-scalable=yes";
    disabledInitially = /(user-scalable[\s]*=[\s]*no)|(maximum-scale[\s]*=[\s]*1)[$,\s]/.test(initialContent);
    umobi.zoom = $.extend({}, {
      enabled: !disabledInitially,
      locked: false,
      disable: function(lock) {
        if (!disabledInitially && !umobi.zoom.locked) {
          meta.attr("content", disabledZoom);
          umobi.zoom.enabled = false;
          return umobi.zoom.locked = lock || false; 
        }
      },
      enable: function(unlock) {
        if (!disabledInitially && (!umobi.zoom.locked || unlock !== true)) {
          meta.attr("content", enabledZoom);
          umobi.zoom.enabled = true;
          return umobi.zoom.locked = false; 
        }
      },
      restore: function() {
        if (!disabledInitially) {
          meta.attr("content", initialContent);
          return umobi.zoom.enabled = true; 
        }
      }
    });
    return umobi.zoom;
  });

}).call(this);
