// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    window.umobi = {
      config: {
        touchScroll: false,
        theme: 'c'
      }
    };
    return window.umobi;
  });

}).call(this);
