// Generated by CoffeeScript 1.4.0
(function() {

  define(["cs!u", "cs!umobi.core"], function() {
    var slider;
    slider = {
      create: function(el) {
        var $a, $btn, $widget;
        $widget = $("<div/>").addClass("ui-slider ui-btn ui-btn-down-c ui-btn-corner-all");
        $a = $("<a/>").addClass("ui-slider-handle ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all");
        $a.addClass("ui-btn-up-c");
        $btn = $("<span/>").addClass("ui-btn-inner ui-btn-corner-all");
        $a.append($btn).appendTo($widget);
        el.type = "number";
        $(el).addClass("ui-btn ui-input-text ui-slider-input ui-btn-corner-all ui-mini ui-inline");
        return $(el).after($widget);
      }
    };
    return u.ready(function() {
      var el, _i, _len, _ref, _results;
      _ref = u('input[type="range"]').all();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        el = _ref[_i];
        _results.push(slider.create(el));
      }
      return _results;
    });
  });

}).call(this);
